[build]
  command = "npm install --legacy-peer-deps --resolve-matrix && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.20.7"
  NPM_VERSION = "10.8.2"
  NPM_FLAGS = "--legacy-peer-deps --resolve-matrix"
